### ISSUE TITLE
adding extensions  Shortcuts ulauncher-session-manager Window Switcher extension NetworkManager

### ISSUE THREAD

**Issue by daktras420** [melianmiko/ulauncher-nmcli#3]
i have tried to add a few extensions in v6 
here is the error details pasted below

message: No extension could be found matching com.github.melianmiko.ulauncher-nmcli
type: AssertionError
stack trace: ```
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/ulauncher/ui/preferences_server.py", line 108, in request_listener
    data = json.dumps([route_handler(self, *args)])
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/ulauncher/ui/preferences_server.py", line 267, in extension_add
    controller = ExtensionController.create_from_url(url)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/ulauncher/modes/extensions/ExtensionController.py", line 81, in create_from_url
    instance = cls(remote.ext_id)
               ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/ulauncher/modes/extensions/ExtensionController.py", line 66, in __init__
    if self.state.url:
       ^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/ulauncher/modes/extensions/ExtensionController.py", line 96, in state
    defaults = json_load(f"{self.path}/.default-state.json")
                            ^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/ulauncher/modes/extensions/ExtensionController.py", line 109, in path
    assert self._path, f"No extension could be found matching {self.id}"
AssertionError: No extension could be found matching com.github.melianmiko.ulauncher-nmcli

message: No extension could be found matching com.github.brpaz.ulauncher-shortcuts
type: AssertionError
stack trace: ```
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/ulauncher/ui/preferences_server.py", line 108, in request_listener
    data = json.dumps([route_handler(self, *args)])
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/ulauncher/ui/preferences_server.py", line 267, in extension_add
    controller = ExtensionController.create_from_url(url)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/ulauncher/modes/extensions/ExtensionController.py", line 81, in create_from_url
    instance = cls(remote.ext_id)
               ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/ulauncher/modes/extensions/ExtensionController.py", line 66, in __init__
    if self.state.url:
       ^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/ulauncher/modes/extensions/ExtensionController.py", line 96, in state
    defaults = json_load(f"{self.path}/.default-state.json")
                            ^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/ulauncher/modes/extensions/ExtensionController.py", line 109, in path
    assert self._path, f"No extension could be found matching {self.id}"
AssertionError: No extension could be found matching com.github.brpaz.ulauncher-shortcuts
message: No extension could be found matching com.github.lighttigerxiv.ulauncher-session-manager
type: AssertionError
stack trace: ```
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/ulauncher/ui/preferences_server.py", line 108, in request_listener
    data = json.dumps([route_handler(self, *args)])
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/ulauncher/ui/preferences_server.py", line 267, in extension_add
    controller = ExtensionController.create_from_url(url)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/ulauncher/modes/extensions/ExtensionController.py", line 81, in create_from_url
    instance = cls(remote.ext_id)
               ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/ulauncher/modes/extensions/ExtensionController.py", line 66, in __init__
    if self.state.url:
       ^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/ulauncher/modes/extensions/ExtensionController.py", line 96, in state
    defaults = json_load(f"{self.path}/.default-state.json")
                            ^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/ulauncher/modes/extensions/ExtensionController.py", line 109, in path
    assert self._path, f"No extension could be found matching {self.id}"
AssertionError: No extension could be found matching com.github.lighttigerxiv.ulauncher-session-manager

```
```

```

**Comment by melianmiko** [comment]
ULuancher v6 isn't stable, return if the same error happen after their release.

![image](https://github.com/melianmiko/ulauncher-nmcli/assets/67851274/6cdccc16-eea8-48cd-8229-233ce252a253)
